-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity folo_pointwise_conv_2d_cl_array_array_ap_fixed_12_6_5_3_0_8u_config36_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer22_out_dout : IN STD_LOGIC_VECTOR (95 downto 0);
    layer22_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer22_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer22_out_empty_n : IN STD_LOGIC;
    layer22_out_read : OUT STD_LOGIC;
    layer23_out_din : OUT STD_LOGIC_VECTOR (95 downto 0);
    layer23_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer23_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    layer23_out_full_n : IN STD_LOGIC;
    layer23_out_write : OUT STD_LOGIC );
end;


architecture behav of folo_pointwise_conv_2d_cl_array_array_ap_fixed_12_6_5_3_0_8u_config36_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer22_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal layer23_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal data_fu_126_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_reg_263 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_1_reg_268 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_2_reg_273 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_3_reg_278 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_4_reg_283 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_5_reg_288 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_6_reg_293 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_7_reg_298 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_reg_303 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done : STD_LOGIC;
    signal res_8_reg_308 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_9_reg_313 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_10_reg_318 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_11_reg_323 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_12_reg_328 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_13_reg_333 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_14_reg_338 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_3 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_4 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_5 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_6 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_7 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start_reg : STD_LOGIC := '0';
    signal indvar_flatten_fu_70 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln81_fu_115_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln81_fu_109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component folo_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (11 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87 : component folo_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start,
        ap_done => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done,
        ap_idle => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_idle,
        ap_ready => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_ready,
        data_0_val => data_reg_263,
        data_1_val => data_1_reg_268,
        data_2_val => data_2_reg_273,
        data_3_val => data_3_reg_278,
        data_4_val => data_4_reg_283,
        data_5_val => data_5_reg_288,
        data_6_val => data_6_reg_293,
        data_7_val => data_7_reg_298,
        ap_return_0 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_3,
        ap_return_4 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_4,
        ap_return_5 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_5,
        ap_return_6 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_6,
        ap_return_7 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_7);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_109_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start_reg <= ap_const_logic_0;
            else
                if (((layer22_out_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                indvar_flatten_fu_70 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_109_p2 = ap_const_lv1_0))) then 
                indvar_flatten_fu_70 <= add_ln81_fu_115_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((layer22_out_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                data_1_reg_268 <= layer22_out_dout(23 downto 12);
                data_2_reg_273 <= layer22_out_dout(35 downto 24);
                data_3_reg_278 <= layer22_out_dout(47 downto 36);
                data_4_reg_283 <= layer22_out_dout(59 downto 48);
                data_5_reg_288 <= layer22_out_dout(71 downto 60);
                data_6_reg_293 <= layer22_out_dout(83 downto 72);
                data_7_reg_298 <= layer22_out_dout(95 downto 84);
                data_reg_263 <= data_fu_126_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                res_10_reg_318 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_3;
                res_11_reg_323 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_4;
                res_12_reg_328 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_5;
                res_13_reg_333 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_6;
                res_14_reg_338 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_7;
                res_8_reg_308 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_1;
                res_9_reg_313 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_2;
                res_reg_303 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer22_out_empty_n, layer23_out_full_n, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state4, grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done, ap_CS_fsm_state2, icmp_ln81_fu_109_p2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_109_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((layer22_out_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln81_fu_115_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_70) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer22_out_empty_n)
    begin
        if ((layer22_out_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done)
    begin
        if ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(layer23_out_full_n)
    begin
        if ((layer23_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln81_fu_109_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_109_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_126_p1 <= layer22_out_dout(12 - 1 downto 0);
    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_12_6_5_3_0_config36_mult_s_fu_87_ap_start_reg;
    icmp_ln81_fu_109_p2 <= "1" when (indvar_flatten_fu_70 = ap_const_lv11_400) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln81_fu_109_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_109_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer22_out_blk_n_assign_proc : process(layer22_out_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer22_out_blk_n <= layer22_out_empty_n;
        else 
            layer22_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer22_out_read_assign_proc : process(layer22_out_empty_n, ap_CS_fsm_state3)
    begin
        if (((layer22_out_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer22_out_read <= ap_const_logic_1;
        else 
            layer22_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer23_out_blk_n_assign_proc : process(layer23_out_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            layer23_out_blk_n <= layer23_out_full_n;
        else 
            layer23_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer23_out_din <= (((((((res_14_reg_338 & res_13_reg_333) & res_12_reg_328) & res_11_reg_323) & res_10_reg_318) & res_9_reg_313) & res_8_reg_308) & res_reg_303);

    layer23_out_write_assign_proc : process(layer23_out_full_n, ap_CS_fsm_state5)
    begin
        if (((layer23_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            layer23_out_write <= ap_const_logic_1;
        else 
            layer23_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
