-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity folo_compute_output_buffer_2d_array_array_ap_fixed_37_17_5_3_0_16u_config3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    layer3_out_din : OUT STD_LOGIC_VECTOR (591 downto 0);
    layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (14 downto 0);
    layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (14 downto 0);
    layer3_out_full_n : IN STD_LOGIC;
    layer3_out_write : OUT STD_LOGIC;
    layer3_out_blk_n : OUT STD_LOGIC );
end;


architecture behav of folo_compute_output_buffer_2d_array_array_ap_fixed_37_17_5_3_0_16u_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln284_reg_397 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_1_reg_401 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal and_ln284_1_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_reg_405 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln313_fu_292_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_out_reg_417 : STD_LOGIC_VECTOR (36 downto 0);
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal res_out_1_reg_422 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_2_reg_427 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_3_reg_432 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_4_reg_437 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_5_reg_442 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_6_reg_447 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_7_reg_452 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_8_reg_457 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_9_reg_462 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_16_reg_467 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_17_reg_472 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_18_reg_477 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_19_reg_482 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_20_reg_487 : STD_LOGIC_VECTOR (36 downto 0);
    signal res_out_21_reg_492 : STD_LOGIC_VECTOR (36 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_predicate_op70_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_start : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_done : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_idle : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ready : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ce : STD_LOGIC;
    signal ap_block_state7_pp0_stage0_iter1_ignore_call2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp9 : BOOLEAN;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_0 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_1 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_2 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_3 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_4 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_5 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_6 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_7 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_8 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_9 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_10 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_11 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_12 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_13 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_14 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_15 : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_ce : STD_LOGIC;
    signal ap_predicate_op25_call_state2 : BOOLEAN;
    signal ap_predicate_op46_call_state3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp25 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_ignoreCallOp46 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage3_11001_ignoreCallOp50 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage4_11001_ignoreCallOp51 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage5_11001_ignoreCallOp52 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_storemerge_reg_79 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln307_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal select_ln318_fu_236_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln307_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln303_fu_212_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_6_fu_168_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_7_fu_184_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln284_7_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_8_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_1_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln318_fu_230_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln313_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln313_fu_286_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_356 : BOOLEAN;
    signal ap_condition_280 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component folo_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;


    component folo_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (36 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90 : component folo_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_start,
        ap_done => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_done,
        ap_idle => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_idle,
        ap_ready => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ready,
        in_elem_0_0_0_0_0_val => in_elem_0_0_0_0_0_val,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld,
        ap_ce => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ce);

    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118 : component folo_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        ap_return_0 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_0,
        ap_return_1 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_1,
        ap_return_2 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_2,
        ap_return_3 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_3,
        ap_return_4 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_4,
        ap_return_5 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_5,
        ap_return_6 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_6,
        ap_return_7 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_7,
        ap_return_8 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_8,
        ap_return_9 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_9,
        ap_return_10 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_10,
        ap_return_11 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_11,
        ap_return_12 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_12,
        ap_return_13 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_13,
        ap_return_14 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_14,
        ap_return_15 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_15,
        ap_ce => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_storemerge_reg_79_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_356)) then
                if ((icmp_ln307_fu_268_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_storemerge_reg_79 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_268_p2 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_storemerge_reg_79 <= select_ln313_fu_292_p3;
                end if;
            end if; 
        end if;
    end process;

    pX_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_280)) then
                if ((icmp_ln303_fu_218_p2 = ap_const_lv1_1)) then 
                    pX_3 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_218_p2 = ap_const_lv1_0)) then 
                    pX_3 <= add_ln303_fu_212_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_356)) then
                if ((icmp_ln307_fu_268_p2 = ap_const_lv1_1)) then 
                    pY_3 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_268_p2 = ap_const_lv1_0)) then 
                    pY_3 <= add_ln307_fu_262_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_280)) then
                if ((icmp_ln303_fu_218_p2 = ap_const_lv1_1)) then 
                    sX_3 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_218_p2 = ap_const_lv1_0)) then 
                    sX_3 <= select_ln318_fu_236_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce))) then
                and_ln284_1_reg_401 <= and_ln284_1_fu_206_p2;
                icmp_ln284_reg_397 <= icmp_ln284_fu_144_p2;
                icmp_ln303_reg_405 <= icmp_ln303_fu_218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                res_out_16_reg_467 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_10;
                res_out_17_reg_472 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_11;
                res_out_18_reg_477 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_12;
                res_out_19_reg_482 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_13;
                res_out_1_reg_422 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_1;
                res_out_20_reg_487 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_14;
                res_out_21_reg_492 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_15;
                res_out_2_reg_427 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_2;
                res_out_3_reg_432 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_3;
                res_out_4_reg_437 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_4;
                res_out_5_reg_442 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_5;
                res_out_6_reg_447 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_6;
                res_out_7_reg_452 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_7;
                res_out_8_reg_457 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_8;
                res_out_9_reg_462 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_9;
                res_out_reg_417 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln303_reg_405 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                sY_3 <= ap_phi_reg_pp0_iter0_storemerge_reg_79;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage5_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_idle_pp0_1to1 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) and (ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln303_fu_212_p2 <= std_logic_vector(unsigned(pX_3) + unsigned(ap_const_lv32_1));
    add_ln307_fu_262_p2 <= std_logic_vector(unsigned(pY_3) + unsigned(ap_const_lv32_1));
    add_ln313_fu_286_p2 <= std_logic_vector(unsigned(sY_3) + unsigned(ap_const_lv32_1));
    add_ln318_fu_230_p2 <= std_logic_vector(unsigned(sX_3) + unsigned(ap_const_lv32_1));
    and_ln284_1_fu_206_p2 <= (icmp_ln284_1_fu_162_p2 and and_ln284_fu_200_p2);
    and_ln284_fu_200_p2 <= (icmp_ln284_8_fu_194_p2 and icmp_ln284_7_fu_178_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage0_iter1_ignore_call2)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp9 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter1_ignore_call2));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_ce, ap_block_state7_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001_ignoreCallOp25 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001_ignoreCallOp46 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage2_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage3_11001_ignoreCallOp50 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage3_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage4_11001_ignoreCallOp51 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage4_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001_ignoreCallOp52 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage5_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_block_state7_pp0_stage0_iter1_assign_proc : process(layer3_out_full_n, ap_predicate_op70_write_state7)
    begin
                ap_block_state7_pp0_stage0_iter1 <= ((layer3_out_full_n = ap_const_logic_0) and (ap_predicate_op70_write_state7 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage0_iter1_ignore_call2_assign_proc : process(layer3_out_full_n, ap_predicate_op70_write_state7)
    begin
                ap_block_state7_pp0_stage0_iter1_ignore_call2 <= ((layer3_out_full_n = ap_const_logic_0) and (ap_predicate_op70_write_state7 = ap_const_boolean_1));
    end process;


    ap_condition_280_assign_proc : process(ap_enable_reg_pp0_iter0, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
                ap_condition_280 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_condition_356_assign_proc : process(ap_enable_reg_pp0_iter0, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln303_fu_218_p2)
    begin
                ap_condition_356 <= ((icmp_ln303_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op25_call_state2_assign_proc : process(icmp_ln284_fu_144_p2, and_ln284_1_fu_206_p2)
    begin
                ap_predicate_op25_call_state2 <= ((icmp_ln284_fu_144_p2 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln284_1_fu_206_p2));
    end process;


    ap_predicate_op46_call_state3_assign_proc : process(icmp_ln284_reg_397, and_ln284_1_reg_401)
    begin
                ap_predicate_op46_call_state3 <= ((ap_const_lv1_1 = and_ln284_1_reg_401) and (icmp_ln284_reg_397 = ap_const_lv1_1));
    end process;


    ap_predicate_op70_write_state7_assign_proc : process(icmp_ln284_reg_397, and_ln284_1_reg_401)
    begin
                ap_predicate_op70_write_state7 <= ((ap_const_lv1_1 = and_ln284_1_reg_401) and (icmp_ln284_reg_397 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp9)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp9) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ce <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_start_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_start <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_90_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_ignoreCallOp25, ap_block_pp0_stage2_11001_ignoreCallOp46, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage3_11001_ignoreCallOp50, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage4_11001_ignoreCallOp51, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage5_11001_ignoreCallOp52)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage5_11001_ignoreCallOp52) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001_ignoreCallOp51) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001_ignoreCallOp50) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001_ignoreCallOp46) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp25) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))))) then 
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config3_mult_s_fu_118_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln284_1_fu_162_p2 <= "1" when (sY_3 = ap_const_lv32_2) else "0";
    icmp_ln284_7_fu_178_p2 <= "1" when (signed(tmp_6_fu_168_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_8_fu_194_p2 <= "1" when (signed(tmp_7_fu_184_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_fu_144_p2 <= "1" when (sX_3 = ap_const_lv32_2) else "0";
    icmp_ln303_fu_218_p2 <= "1" when (add_ln303_fu_212_p2 = ap_const_lv32_82) else "0";
    icmp_ln307_fu_268_p2 <= "1" when (add_ln307_fu_262_p2 = ap_const_lv32_82) else "0";
    icmp_ln313_fu_280_p2 <= "1" when (sY_3 = ap_const_lv32_2) else "0";

    layer3_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer3_out_full_n, ap_block_pp0_stage0, icmp_ln284_reg_397, and_ln284_1_reg_401)
    begin
        if (((ap_const_lv1_1 = and_ln284_1_reg_401) and (icmp_ln284_reg_397 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer3_out_blk_n <= layer3_out_full_n;
        else 
            layer3_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer3_out_din <= (((((((((((((((res_out_21_reg_492 & res_out_20_reg_487) & res_out_19_reg_482) & res_out_18_reg_477) & res_out_17_reg_472) & res_out_16_reg_467) & res_out_9_reg_462) & res_out_8_reg_457) & res_out_7_reg_452) & res_out_6_reg_447) & res_out_5_reg_442) & res_out_4_reg_437) & res_out_3_reg_432) & res_out_2_reg_427) & res_out_1_reg_422) & res_out_reg_417);

    layer3_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_predicate_op70_write_state7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op70_write_state7 = ap_const_boolean_1))) then 
            layer3_out_write <= ap_const_logic_1;
        else 
            layer3_out_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln313_fu_292_p3 <= 
        ap_const_lv32_2 when (icmp_ln313_fu_280_p2(0) = '1') else 
        add_ln313_fu_286_p2;
    select_ln318_fu_236_p3 <= 
        ap_const_lv32_2 when (icmp_ln284_fu_144_p2(0) = '1') else 
        add_ln318_fu_230_p2;
    tmp_6_fu_168_p4 <= pY_3(31 downto 1);
    tmp_7_fu_184_p4 <= pX_3(31 downto 1);
end behav;
