-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity folo_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    layer2_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    layer2_out_full_n : IN STD_LOGIC;
    layer2_out_write : OUT STD_LOGIC;
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (17 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (17 downto 0);
    layer2_out_blk_n : OUT STD_LOGIC );
end;


architecture behav of folo_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_101 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sX_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln284_reg_336 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_5_reg_346 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op52_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal sY_5_load_reg_340 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln284_5_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_reg_350 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln307_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln307_reg_354 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_out_reg_358 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal res_out_38_reg_363 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_39_reg_368 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_40_reg_373 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_start : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_done : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_idle : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ready : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ce : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter1_ignore_call2_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp7_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_done : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_idle : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ready : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ce : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_predicate_op39_call_state2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp39 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage2_11001_ignoreCallOp46 : BOOLEAN;
    signal ap_phi_mux_storemerge_phi_fu_83_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln313_fu_299_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp7_grp0 : BOOLEAN;
    signal grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_predicate_op39_call_state2_state1 : BOOLEAN;
    signal ap_block_pp0_stage1_ignoreCallOp39 : BOOLEAN;
    signal add_ln318_fu_238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln307_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln303_fu_212_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal tmp_868_fu_168_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_869_fu_184_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln284_14_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_15_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_13_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln318_fu_230_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln313_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln313_fu_291_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_230 : BOOLEAN;
    signal ap_condition_285 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component folo_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o_ap_vld : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;


    component folo_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90 : component folo_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_start,
        ap_done => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_done,
        ap_idle => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_idle,
        ap_ready => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ready,
        in_elem_0_0_0_0_0_val => in_elem_0_0_0_0_0_val,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o_ap_vld,
        ap_ce => call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ce);

    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118 : component folo_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start,
        ap_done => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_done,
        ap_idle => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_idle,
        ap_ready => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ready,
        ap_ce => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ce,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50,
        ap_return_0 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_0,
        ap_return_1 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_1,
        ap_return_2 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_2,
        ap_return_3 => grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= ap_const_boolean_0;
            else
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op39_call_state2_state1 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    pX_5_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_230)) then
                if ((icmp_ln303_fu_218_p2 = ap_const_lv1_1)) then 
                    pX_5 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_218_p2 = ap_const_lv1_0)) then 
                    pX_5 <= add_ln303_fu_212_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_5_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_285)) then
                if ((icmp_ln307_fu_268_p2 = ap_const_lv1_1)) then 
                    pY_5 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_268_p2 = ap_const_lv1_0)) then 
                    pY_5 <= add_ln307_fu_262_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_5_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_230)) then
                if ((icmp_ln303_fu_218_p2 = ap_const_lv1_1)) then 
                    sX_5 <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_218_p2 = ap_const_lv1_0)) then 
                    sX_5 <= add_ln318_fu_238_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln284_5_reg_346 <= and_ln284_5_fu_206_p2;
                icmp_ln284_reg_336 <= icmp_ln284_fu_144_p2;
                icmp_ln303_reg_350 <= icmp_ln303_fu_218_p2;
                icmp_ln307_reg_354 <= icmp_ln307_fu_268_p2;
                sY_5_load_reg_340 <= sY_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                res_out_38_reg_363 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_1;
                res_out_39_reg_368 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_2;
                res_out_40_reg_373 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_3;
                res_out_reg_358 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln303_reg_350 = ap_const_lv1_1))) then
                sY_5 <= ap_phi_mux_storemerge_phi_fu_83_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_50_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_51_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_52;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_53_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_54_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_55;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_56_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_57_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58 <= call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_58;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_reset_init_pp0, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_reset_init_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_reset_init_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln303_fu_212_p2 <= std_logic_vector(unsigned(pX_5) + unsigned(ap_const_lv32_1));
    add_ln307_fu_262_p2 <= std_logic_vector(unsigned(pY_5) + unsigned(ap_const_lv32_1));
    add_ln313_fu_299_p2 <= std_logic_vector(unsigned(sY_5_load_reg_340) + unsigned(select_ln313_fu_291_p3));
    add_ln318_fu_238_p2 <= std_logic_vector(unsigned(sX_5) + unsigned(select_ln318_fu_230_p3));
    and_ln284_5_fu_206_p2 <= (icmp_ln284_13_fu_162_p2 and and_ln284_fu_200_p2);
    and_ln284_fu_200_p2 <= (icmp_ln284_15_fu_194_p2 and icmp_ln284_14_fu_178_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage0_iter1_ignore_call2_grp1)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp7 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1_ignore_call2_grp1));
    end process;

        ap_block_pp0_stage0_11001_ignoreCallOp7_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp7_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_ce, ap_block_state4_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1_grp1)));
    end process;


    ap_block_pp0_stage0_subdone_grp0_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone_grp0 <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001_ignoreCallOp39 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_ignoreCallOp39 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001_ignoreCallOp46 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage2_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_block_state4_pp0_stage0_iter1_grp1_assign_proc : process(layer2_out_full_n, ap_predicate_op52_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter1_grp1 <= ((ap_predicate_op52_write_state4 = ap_const_boolean_1) and (layer2_out_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter1_ignore_call2_grp1_assign_proc : process(layer2_out_full_n, ap_predicate_op52_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter1_ignore_call2_grp1 <= ((ap_predicate_op52_write_state4 = ap_const_boolean_1) and (layer2_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_230_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001_grp1)
    begin
                ap_condition_230 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_285_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001_grp1, icmp_ln303_fu_218_p2)
    begin
                ap_condition_285 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln303_fu_218_p2 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_83_p4_assign_proc : process(icmp_ln303_reg_350, icmp_ln307_reg_354, add_ln313_fu_299_p2)
    begin
        if (((icmp_ln307_reg_354 = ap_const_lv1_0) and (icmp_ln303_reg_350 = ap_const_lv1_1))) then 
            ap_phi_mux_storemerge_phi_fu_83_p4 <= add_ln313_fu_299_p2;
        else 
            ap_phi_mux_storemerge_phi_fu_83_p4 <= ap_const_lv32_0;
        end if; 
    end process;


    ap_predicate_op39_call_state2_assign_proc : process(icmp_ln284_reg_336, and_ln284_5_reg_346)
    begin
                ap_predicate_op39_call_state2 <= ((ap_const_lv1_1 = and_ln284_5_reg_346) and (icmp_ln284_reg_336 = ap_const_lv1_1));
    end process;


    ap_predicate_op39_call_state2_state1_assign_proc : process(icmp_ln284_fu_144_p2, and_ln284_5_fu_206_p2)
    begin
                ap_predicate_op39_call_state2_state1 <= ((icmp_ln284_fu_144_p2 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln284_5_fu_206_p2));
    end process;


    ap_predicate_op52_write_state4_assign_proc : process(icmp_ln284_reg_336, and_ln284_5_reg_346)
    begin
                ap_predicate_op52_write_state4 <= ((ap_const_lv1_1 = and_ln284_5_reg_346) and (icmp_ln284_reg_336 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to0)
    begin
        if ((ap_idle_pp0_0to0 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp7_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp7_grp0) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ce <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_start_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_grp0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_start <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_90_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_ce, ap_block_pp0_stage1_11001_ignoreCallOp39, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2_11001_ignoreCallOp46)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_ignoreCallOp46) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp39) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))))) then 
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_118_ap_start_reg;
    icmp_ln284_13_fu_162_p2 <= "1" when (sY_5 = ap_const_lv32_2) else "0";
    icmp_ln284_14_fu_178_p2 <= "1" when (signed(tmp_868_fu_168_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_15_fu_194_p2 <= "1" when (signed(tmp_869_fu_184_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_fu_144_p2 <= "1" when (sX_5 = ap_const_lv32_2) else "0";
    icmp_ln303_fu_218_p2 <= "1" when (add_ln303_fu_212_p2 = ap_const_lv32_101) else "0";
    icmp_ln307_fu_268_p2 <= "1" when (add_ln307_fu_262_p2 = ap_const_lv32_101) else "0";
    icmp_ln313_fu_286_p2 <= "1" when (sY_5_load_reg_340 = ap_const_lv32_2) else "0";

    layer2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer2_out_full_n, ap_block_pp0_stage0_grp1, icmp_ln284_reg_336, and_ln284_5_reg_346)
    begin
        if (((ap_const_lv1_1 = and_ln284_5_reg_346) and (icmp_ln284_reg_336 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_blk_n <= layer2_out_full_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer2_out_din <= (((res_out_40_reg_373 & res_out_39_reg_368) & res_out_38_reg_363) & res_out_reg_358);

    layer2_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_predicate_op52_write_state4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_predicate_op52_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_out_write <= ap_const_logic_1;
        else 
            layer2_out_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln313_fu_291_p3 <= 
        ap_const_lv32_FFFFFFFF when (icmp_ln313_fu_286_p2(0) = '1') else 
        ap_const_lv32_1;
    select_ln318_fu_230_p3 <= 
        ap_const_lv32_FFFFFFFF when (icmp_ln284_fu_144_p2(0) = '1') else 
        ap_const_lv32_1;
    tmp_868_fu_168_p4 <= pY_5(31 downto 1);
    tmp_869_fu_184_p4 <= pX_5(31 downto 1);
end behav;
