// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module folo_normalize_array_ap_fixed_8u_array_ap_fixed_12_6_5_3_0_8u_config20_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer20_out_din,
        layer20_out_num_data_valid,
        layer20_out_fifo_cap,
        layer20_out_full_n,
        layer20_out_write,
        layer19_out_dout,
        layer19_out_num_data_valid,
        layer19_out_fifo_cap,
        layer19_out_empty_n,
        layer19_out_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [95:0] layer20_out_din;
input  [10:0] layer20_out_num_data_valid;
input  [10:0] layer20_out_fifo_cap;
input   layer20_out_full_n;
output   layer20_out_write;
input  [95:0] layer19_out_dout;
input  [10:0] layer19_out_num_data_valid;
input  [10:0] layer19_out_fifo_cap;
input   layer19_out_empty_n;
output   layer19_out_read;

reg ap_idle;
reg layer20_out_write;
reg layer19_out_read;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln25_fu_10946_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    layer19_out_blk_n;
wire    ap_CS_fsm_state2;
reg    layer20_out_blk_n;
wire   [17:0] mul_ln42_fu_512_p2;
reg   [17:0] mul_ln42_reg_10917;
wire    ap_CS_fsm_state3;
wire   [17:0] mul_ln42_1_fu_258_p2;
reg   [17:0] mul_ln42_1_reg_10921;
wire   [17:0] mul_ln42_2_fu_359_p2;
reg   [17:0] mul_ln42_2_reg_10925;
wire   [17:0] mul_ln42_3_fu_524_p2;
reg   [17:0] mul_ln42_3_reg_10929;
wire   [17:0] mul_ln42_4_fu_148_p2;
reg   [17:0] mul_ln42_4_reg_10933;
reg  signed [11:0] a_reg_11298;
reg    ap_block_state2_pp0_stage1_iter0;
reg  signed [11:0] a_1_reg_11303;
reg  signed [11:0] a_2_reg_11308;
reg  signed [11:0] a_3_reg_11313;
reg  signed [11:0] a_4_reg_11318;
wire   [11:0] trunc_ln73_fu_11013_p1;
reg   [11:0] trunc_ln73_reg_11323;
reg   [11:0] tmp_2_reg_11329;
reg   [11:0] tmp_4_reg_11335;
reg   [11:0] trunc_ln_reg_11341;
reg   [11:0] trunc_ln41_3_reg_11346;
reg   [10:0] i_02_fu_128;
wire   [10:0] i_17_fu_10952_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i;
wire   [7:0] mul_ln42_4_fu_148_p1;
wire   [7:0] mul_ln42_1_fu_258_p1;
wire   [6:0] mul_ln42_2_fu_359_p1;
wire   [7:0] mul_ln42_fu_512_p1;
wire   [6:0] mul_ln42_3_fu_524_p1;
wire   [16:0] shl_ln_fu_11037_p3;
wire   [13:0] shl_ln73_1_fu_11048_p3;
wire  signed [14:0] sext_ln42_5_fu_11055_p1;
wire   [14:0] add_ln42_8_fu_11059_p2;
wire  signed [17:0] sext_ln42_6_fu_11065_p1;
wire  signed [17:0] sext_ln73_fu_11044_p1;
wire   [17:0] add_ln42_fu_11069_p2;
wire   [14:0] and_ln73_1_fu_11100_p3;
wire  signed [15:0] sext_ln42_7_fu_11107_p1;
wire   [15:0] add_ln42_9_fu_11111_p2;
wire  signed [17:0] sext_ln42_8_fu_11117_p1;
wire   [17:0] and_ln_fu_11093_p3;
wire   [17:0] add_ln42_3_fu_11121_p2;
wire   [17:0] add_ln42_1_fu_11149_p2;
wire   [17:0] add_ln42_2_fu_11165_p2;
wire   [17:0] add_ln42_4_fu_11181_p2;
wire   [15:0] and_ln73_3_fu_11204_p3;
wire   [17:0] and_ln73_2_fu_11197_p3;
wire  signed [17:0] sext_ln73_1_fu_11211_p1;
wire   [17:0] sub_ln73_fu_11215_p2;
wire   [17:0] add_ln42_5_fu_11221_p2;
wire   [17:0] add_ln42_6_fu_11237_p2;
wire   [17:0] add_ln42_7_fu_11253_p2;
wire   [11:0] trunc_ln41_7_fu_11259_p4;
wire   [11:0] trunc_ln41_6_fu_11243_p4;
wire   [11:0] trunc_ln41_5_fu_11227_p4;
wire   [11:0] trunc_ln41_4_fu_11187_p4;
wire   [11:0] trunc_ln41_2_fu_11171_p4;
wire   [11:0] trunc_ln41_1_fu_11155_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_done_reg = 1'b0;
#0 i_02_fu_128 = 11'd0;
end

folo_mul_12s_8ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mul_12s_8ns_18_1_1_U822(
    .din0(a_4_reg_11318),
    .din1(mul_ln42_4_fu_148_p1),
    .dout(mul_ln42_4_fu_148_p2)
);

folo_mul_12s_8ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mul_12s_8ns_18_1_1_U823(
    .din0(a_1_reg_11303),
    .din1(mul_ln42_1_fu_258_p1),
    .dout(mul_ln42_1_fu_258_p2)
);

folo_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U824(
    .din0(a_2_reg_11308),
    .din1(mul_ln42_2_fu_359_p1),
    .dout(mul_ln42_2_fu_359_p2)
);

folo_mul_12s_8ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 18 ))
mul_12s_8ns_18_1_1_U825(
    .din0(a_reg_11298),
    .din1(mul_ln42_fu_512_p1),
    .dout(mul_ln42_fu_512_p2)
);

folo_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U826(
    .din0(a_3_reg_11313),
    .din1(mul_ln42_3_fu_524_p1),
    .dout(mul_ln42_3_fu_524_p2)
);

folo_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln25_fu_10946_p2 == 1'd0)) begin
            i_02_fu_128 <= i_17_fu_10952_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_02_fu_128 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        a_1_reg_11303 <= {{layer19_out_dout[35:24]}};
        a_2_reg_11308 <= {{layer19_out_dout[59:48]}};
        a_3_reg_11313 <= {{layer19_out_dout[83:72]}};
        a_4_reg_11318 <= {{layer19_out_dout[95:84]}};
        a_reg_11298 <= {{layer19_out_dout[23:12]}};
        tmp_2_reg_11329 <= {{layer19_out_dout[47:36]}};
        tmp_4_reg_11335 <= {{layer19_out_dout[71:60]}};
        trunc_ln73_reg_11323 <= trunc_ln73_fu_11013_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln42_1_reg_10921 <= mul_ln42_1_fu_258_p2;
        mul_ln42_2_reg_10925 <= mul_ln42_2_fu_359_p2;
        mul_ln42_3_reg_10929 <= mul_ln42_3_fu_524_p2;
        mul_ln42_4_reg_10933 <= mul_ln42_4_fu_148_p2;
        mul_ln42_reg_10917 <= mul_ln42_fu_512_p2;
        trunc_ln41_3_reg_11346 <= {{add_ln42_3_fu_11121_p2[17:6]}};
        trunc_ln_reg_11341 <= {{add_ln42_fu_11069_p2[17:6]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_pp0_stage3_iter0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_10946_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 11'd0;
    end else begin
        ap_sig_allocacmp_i = i_02_fu_128;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer19_out_blk_n = layer19_out_empty_n;
    end else begin
        layer19_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer19_out_read = 1'b1;
    end else begin
        layer19_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer20_out_blk_n = layer20_out_full_n;
    end else begin
        layer20_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
        layer20_out_write = 1'b1;
    end else begin
        layer20_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln25_fu_10946_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_pp0_stage3_iter0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_1_fu_11149_p2 = ($signed(mul_ln42_reg_10917) + $signed(18'd246912));

assign add_ln42_2_fu_11165_p2 = (mul_ln42_1_reg_10921 + 18'd7808);

assign add_ln42_3_fu_11121_p2 = ($signed(sext_ln42_8_fu_11117_p1) + $signed(and_ln_fu_11093_p3));

assign add_ln42_4_fu_11181_p2 = ($signed(mul_ln42_2_reg_10925) + $signed(18'd256256));

assign add_ln42_5_fu_11221_p2 = (sub_ln73_fu_11215_p2 + 18'd8576);

assign add_ln42_6_fu_11237_p2 = ($signed(mul_ln42_3_reg_10929) + $signed(18'd261376));

assign add_ln42_7_fu_11253_p2 = (mul_ln42_4_reg_10933 + 18'd9280);

assign add_ln42_8_fu_11059_p2 = ($signed(sext_ln42_5_fu_11055_p1) + $signed(15'd28800));

assign add_ln42_9_fu_11111_p2 = ($signed(sext_ln42_7_fu_11107_p1) + $signed(16'd13184));

assign add_ln42_fu_11069_p2 = ($signed(sext_ln42_6_fu_11065_p1) + $signed(sext_ln73_fu_11044_p1));

assign and_ln73_1_fu_11100_p3 = {{tmp_2_reg_11329}, {3'd0}};

assign and_ln73_2_fu_11197_p3 = {{tmp_4_reg_11335}, {6'd0}};

assign and_ln73_3_fu_11204_p3 = {{tmp_4_reg_11335}, {4'd0}};

assign and_ln_fu_11093_p3 = {{tmp_2_reg_11329}, {6'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (layer19_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = (layer20_out_full_n == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_17_fu_10952_p2 = (ap_sig_allocacmp_i + 11'd1);

assign icmp_ln25_fu_10946_p2 = ((ap_sig_allocacmp_i == 11'd1024) ? 1'b1 : 1'b0);

assign layer20_out_din = {{{{{{{{trunc_ln41_7_fu_11259_p4}, {trunc_ln41_6_fu_11243_p4}}, {trunc_ln41_5_fu_11227_p4}}, {trunc_ln41_4_fu_11187_p4}}, {trunc_ln41_3_reg_11346}}, {trunc_ln41_2_fu_11171_p4}}, {trunc_ln41_1_fu_11155_p4}}, {trunc_ln_reg_11341}};

assign mul_ln42_1_fu_258_p1 = 18'd78;

assign mul_ln42_2_fu_359_p1 = 18'd53;

assign mul_ln42_3_fu_524_p1 = 18'd50;

assign mul_ln42_4_fu_148_p1 = 18'd95;

assign mul_ln42_fu_512_p1 = 18'd86;

assign sext_ln42_5_fu_11055_p1 = $signed(shl_ln73_1_fu_11048_p3);

assign sext_ln42_6_fu_11065_p1 = $signed(add_ln42_8_fu_11059_p2);

assign sext_ln42_7_fu_11107_p1 = $signed(and_ln73_1_fu_11100_p3);

assign sext_ln42_8_fu_11117_p1 = $signed(add_ln42_9_fu_11111_p2);

assign sext_ln73_1_fu_11211_p1 = $signed(and_ln73_3_fu_11204_p3);

assign sext_ln73_fu_11044_p1 = $signed(shl_ln_fu_11037_p3);

assign shl_ln73_1_fu_11048_p3 = {{trunc_ln73_reg_11323}, {2'd0}};

assign shl_ln_fu_11037_p3 = {{trunc_ln73_reg_11323}, {5'd0}};

assign sub_ln73_fu_11215_p2 = ($signed(and_ln73_2_fu_11197_p3) - $signed(sext_ln73_1_fu_11211_p1));

assign trunc_ln41_1_fu_11155_p4 = {{add_ln42_1_fu_11149_p2[17:6]}};

assign trunc_ln41_2_fu_11171_p4 = {{add_ln42_2_fu_11165_p2[17:6]}};

assign trunc_ln41_4_fu_11187_p4 = {{add_ln42_4_fu_11181_p2[17:6]}};

assign trunc_ln41_5_fu_11227_p4 = {{add_ln42_5_fu_11221_p2[17:6]}};

assign trunc_ln41_6_fu_11243_p4 = {{add_ln42_6_fu_11237_p2[17:6]}};

assign trunc_ln41_7_fu_11259_p4 = {{add_ln42_7_fu_11253_p2[17:6]}};

assign trunc_ln73_fu_11013_p1 = layer19_out_dout[11:0];

endmodule //folo_normalize_array_ap_fixed_8u_array_ap_fixed_12_6_5_3_0_8u_config20_s
