// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module folo_sigmoid_array_array_ap_fixed_12_6_5_3_0_1u_sigmoid_config26_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer25_out_dout,
        layer25_out_num_data_valid,
        layer25_out_fifo_cap,
        layer25_out_empty_n,
        layer25_out_read,
        layer26_out_TREADY,
        layer26_out_TDATA,
        layer26_out_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] layer25_out_dout;
input  [10:0] layer25_out_num_data_valid;
input  [10:0] layer25_out_fifo_cap;
input   layer25_out_empty_n;
output   layer25_out_read;
input   layer26_out_TREADY;
output  [15:0] layer26_out_TDATA;
output   layer26_out_TVALID;

reg ap_idle;
reg layer25_out_read;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    regslice_both_layer26_out_U_apdone_blk;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state5_pp0_stage0_iter4;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln80_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire   [9:0] sigmoid_table_address0;
reg    sigmoid_table_ce0;
wire   [9:0] sigmoid_table_q0;
reg    layer25_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer26_out_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] index_fu_127_p2;
reg   [12:0] index_reg_216;
reg   [0:0] tmp_reg_221;
reg   [2:0] tmp_1_reg_227;
wire   [63:0] zext_ln96_fu_185_p1;
reg   [10:0] i_fu_68;
wire   [10:0] i_14_fu_112_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_13;
reg    ap_block_pp0_stage0_01001;
wire  signed [12:0] sext_ln90_fu_123_p1;
wire   [0:0] xor_ln92_fu_159_p2;
wire   [0:0] icmp_ln94_fu_154_p2;
wire   [0:0] or_ln92_fu_172_p2;
wire   [9:0] select_ln92_fu_164_p3;
wire   [9:0] trunc_ln91_fu_151_p1;
wire   [9:0] index_1_fu_177_p3;
wire   [5:0] lshr_ln_fu_190_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] layer26_out_TDATA_int_regslice;
reg    layer26_out_TVALID_int_regslice;
wire    layer26_out_TREADY_int_regslice;
wire    regslice_both_layer26_out_U_vld_out;
reg    ap_condition_141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_68 = 11'd0;
end

folo_sigmoid_array_array_ap_fixed_12_6_5_3_0_1u_sigmoid_config26_s_sigmoid_table_Rbfk #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sigmoid_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_table_address0),
    .ce0(sigmoid_table_ce0),
    .q0(sigmoid_table_q0)
);

folo_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

folo_regslice_both #(
    .DataWidth( 16 ))
regslice_both_layer26_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(layer26_out_TDATA_int_regslice),
    .vld_in(layer26_out_TVALID_int_regslice),
    .ack_in(layer26_out_TREADY_int_regslice),
    .data_out(layer26_out_TDATA),
    .vld_out(regslice_both_layer26_out_U_vld_out),
    .ack_out(layer26_out_TREADY),
    .apdone_blk(regslice_both_layer26_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln80_fu_106_p2 == 1'd0)) begin
            i_fu_68 <= i_14_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        index_reg_216 <= index_fu_127_p2;
        tmp_1_reg_227 <= {{index_fu_127_p2[12:10]}};
        tmp_reg_221 <= index_fu_127_p2[32'd12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_13 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_13 = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer25_out_blk_n = layer25_out_empty_n;
    end else begin
        layer25_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer25_out_read = 1'b1;
    end else begin
        layer25_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        layer26_out_TDATA_blk_n = layer26_out_TREADY_int_regslice;
    end else begin
        layer26_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer26_out_TVALID_int_regslice = 1'b1;
    end else begin
        layer26_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sigmoid_table_ce0 = 1'b1;
    end else begin
        sigmoid_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (regslice_both_layer26_out_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (regslice_both_layer26_out_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & ((layer26_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & ((layer26_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (regslice_both_layer26_out_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & ((layer26_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & ((layer26_out_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer25_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((regslice_both_layer26_out_U_apdone_blk == 1'b1) | (layer26_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (layer26_out_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_141 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_14_fu_112_p2 = (ap_sig_allocacmp_i_13 + 11'd1);

assign icmp_ln80_fu_106_p2 = ((ap_sig_allocacmp_i_13 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_154_p2 = ((tmp_1_reg_227 != 3'd0) ? 1'b1 : 1'b0);

assign index_1_fu_177_p3 = ((or_ln92_fu_172_p2[0:0] == 1'b1) ? select_ln92_fu_164_p3 : trunc_ln91_fu_151_p1);

assign index_fu_127_p2 = ($signed(sext_ln90_fu_123_p1) + $signed(13'd512));

assign layer26_out_TDATA_int_regslice = lshr_ln_fu_190_p4;

assign layer26_out_TVALID = regslice_both_layer26_out_U_vld_out;

assign lshr_ln_fu_190_p4 = {{sigmoid_table_q0[9:4]}};

assign or_ln92_fu_172_p2 = (tmp_reg_221 | icmp_ln94_fu_154_p2);

assign select_ln92_fu_164_p3 = ((xor_ln92_fu_159_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign sext_ln90_fu_123_p1 = $signed(layer25_out_dout);

assign sigmoid_table_address0 = zext_ln96_fu_185_p1;

assign trunc_ln91_fu_151_p1 = index_reg_216[9:0];

assign xor_ln92_fu_159_p2 = (tmp_reg_221 ^ 1'd1);

assign zext_ln96_fu_185_p1 = index_1_fu_177_p3;

endmodule //folo_sigmoid_array_array_ap_fixed_12_6_5_3_0_1u_sigmoid_config26_s
