// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module folo_pointwise_conv_2d_cl_array_array_ap_fixed_30_12_5_3_0_8u_config36_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer22_out_dout,
        layer22_out_empty_n,
        layer22_out_read,
        layer22_out_num_data_valid,
        layer22_out_fifo_cap,
        layer23_out_din,
        layer23_out_full_n,
        layer23_out_write,
        layer23_out_num_data_valid,
        layer23_out_fifo_cap
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [79:0] layer22_out_dout;
input   layer22_out_empty_n;
output   layer22_out_read;
input  [2:0] layer22_out_num_data_valid;
input  [2:0] layer22_out_fifo_cap;
output  [239:0] layer23_out_din;
input   layer23_out_full_n;
output   layer23_out_write;
input  [1:0] layer23_out_num_data_valid;
input  [1:0] layer23_out_fifo_cap;

reg ap_idle;
reg start_write;
reg layer22_out_read;
reg layer23_out_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln67_reg_292;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer22_out_blk_n;
reg    ap_done_reg;
wire    ap_block_pp0_stage0_grp1;
reg    layer23_out_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp2;
wire   [9:0] data_fu_109_p1;
reg   [9:0] data_reg_252;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [9:0] data_8_reg_257;
reg   [9:0] data_9_reg_262;
reg   [9:0] data_10_reg_267;
reg   [9:0] data_1_reg_272;
reg   [9:0] data_2_reg_277;
reg   [9:0] data_3_reg_282;
reg   [9:0] data_4_reg_287;
wire   [0:0] icmp_ln67_fu_189_p2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln67_reg_292_pp0_iter1_reg;
reg   [29:0] res_reg_296;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
reg    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
reg   [29:0] res_1_reg_301;
reg   [29:0] res_2_reg_306;
reg   [29:0] res_3_reg_311;
reg   [29:0] res_4_reg_316;
reg   [29:0] res_5_reg_321;
reg   [29:0] res_6_reg_326;
reg   [29:0] res_7_reg_331;
reg    ap_block_pp0_stage1_subdone;
wire    grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start;
wire    grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_done;
wire    grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_idle;
wire    grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ready;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_0;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_1;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_2;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_3;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_4;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_5;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_6;
wire   [29:0] grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_7;
reg    grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ce;
reg    ap_block_pp0_stage1_11001_ignoreCallOp32;
reg    ap_block_pp0_stage2_11001_ignoreCallOp33;
wire    ap_block_pp0_stage3_11001_ignoreCallOp34;
wire    ap_block_pp0_stage4_11001_ignoreCallOp35;
wire    ap_block_pp0_stage5_11001_ignoreCallOp36;
wire    ap_block_pp0_stage6_11001_ignoreCallOp37;
wire    ap_block_pp0_stage7_11001_ignoreCallOp38;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call13_grp1;
reg    ap_block_pp0_stage0_11001_ignoreCallOp39;
wire    ap_block_pp0_stage1_11001_ignoreCallOp32_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_CS_fsm_pp0_stage6;
reg    ap_block_pp0_stage0_11001_ignoreCallOp39_grp0;
reg    grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start_reg;
wire    ap_block_pp0_stage1_ignoreCallOp32_grp0;
reg   [9:0] indvar_flatten2_fu_72;
wire   [9:0] add_ln67_fu_183_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_indvar_flatten2_load;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage1_01001_grp2;
reg    ap_block_pp0_stage1_11001_grp2;
wire    ap_block_pp0_stage0_grp0;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage7_11001;
reg    ap_condition_exit_pp0_iter1_stage1;
reg    ap_idle_pp0_0to0;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_281;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start_reg = 1'b0;
#0 indvar_flatten2_fu_72 = 10'd0;
end

folo_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ready),
    .data_0_val(data_reg_252),
    .data_1_val(data_8_reg_257),
    .data_2_val(data_9_reg_262),
    .data_3_val(data_10_reg_267),
    .data_4_val(data_1_reg_272),
    .data_5_val(data_2_reg_277),
    .data_6_val(data_3_reg_282),
    .data_7_val(data_4_reg_287),
    .ap_return_0(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_7),
    .ap_ce(grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ce)
);

folo_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_281)) begin
        indvar_flatten2_fu_72 <= add_ln67_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_10_reg_267 <= {{layer22_out_dout[39:30]}};
        data_1_reg_272 <= {{layer22_out_dout[49:40]}};
        data_2_reg_277 <= {{layer22_out_dout[59:50]}};
        data_3_reg_282 <= {{layer22_out_dout[69:60]}};
        data_4_reg_287 <= {{layer22_out_dout[79:70]}};
        data_8_reg_257 <= {{layer22_out_dout[19:10]}};
        data_9_reg_262 <= {{layer22_out_dout[29:20]}};
        data_reg_252 <= data_fu_109_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln67_reg_292 <= icmp_ln67_fu_189_p2;
        icmp_ln67_reg_292_pp0_iter1_reg <= icmp_ln67_reg_292;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_1_reg_301 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_1;
        res_2_reg_306 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_2;
        res_3_reg_311 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_3;
        res_4_reg_316 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_4;
        res_5_reg_321 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_5;
        res_6_reg_326 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_6;
        res_7_reg_331 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_7;
        res_reg_296 <= grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_return_0;
    end
end

always @ (*) begin
    if (((icmp_ln67_reg_292 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln67_reg_292_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_72;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp39_grp0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001_ignoreCallOp38) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001_ignoreCallOp37) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001_ignoreCallOp36) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp35) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp34) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp33) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp32_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer22_out_blk_n = layer22_out_empty_n;
    end else begin
        layer22_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer22_out_read = 1'b1;
    end else begin
        layer22_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer23_out_blk_n = layer23_out_full_n;
    end else begin
        layer23_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer23_out_write = 1'b1;
    end else begin
        layer23_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_fu_183_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp39 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call13_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp39_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp2 = ((layer23_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((layer23_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp32 = ((layer23_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage1_11001_ignoreCallOp32_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp32_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((layer23_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_ignoreCallOp33 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage3_11001_ignoreCallOp34 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_ignoreCallOp35 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001_ignoreCallOp36 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001_ignoreCallOp37 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001_ignoreCallOp38 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (layer22_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call13_grp1 = ((ap_done_reg == 1'b1) | (layer22_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_281 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = internal_ap_ready;

assign data_fu_109_p1 = layer22_out_dout[9:0];

assign grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start = grp_dense_latency_ap_fixed_ap_fixed_30_12_5_3_0_config36_mult_s_fu_89_ap_start_reg;

assign icmp_ln67_fu_189_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 10'd1023) ? 1'b1 : 1'b0);

assign layer23_out_din = {{{{{{{{res_7_reg_331}, {res_6_reg_326}}, {res_5_reg_321}}, {res_4_reg_316}}, {res_3_reg_311}}, {res_2_reg_306}}, {res_1_reg_301}}, {res_reg_296}};

assign start_out = real_start;

endmodule //folo_pointwise_conv_2d_cl_array_array_ap_fixed_30_12_5_3_0_8u_config36_s
