Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision: fixed<12,6>
    ReuseFactor: 16
    Strategy: Resource
    TraceOutput: false
IOType: io_stream
InputData: null
InputShapes:
  input_layer:
  - 256
  - 256
  - 1
KerasModel: !keras_model '../folo_hls4ml/keras_model.keras'
OutputDir: ../folo_hls4ml
OutputPredictions: null
OutputShapes:
  layer26_out:
  - 32
  - 32
  - 1
Part: xcku035-fbva676-2-e
ProjectName: folo
Stamp: ee7df95d
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
