// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module folo_thresholded_relu_array_ap_fixed_array_ap_fixed_16u_thresholdedrelu_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer3_out_dout,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer3_out_empty_n,
        layer3_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [591:0] layer3_out_dout;
input  [14:0] layer3_out_num_data_valid;
input  [14:0] layer3_out_fifo_cap;
input   layer3_out_empty_n;
output   layer3_out_read;
output  [255:0] layer5_out_din;
input  [14:0] layer5_out_num_data_valid;
input  [14:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer3_out_read;
reg layer5_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln528_fu_195_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer3_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer5_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln538_fu_366_p2;
reg   [0:0] icmp_ln538_reg_766;
reg   [15:0] out_data_reg_771;
wire   [0:0] icmp_ln538_16_fu_382_p2;
reg   [0:0] icmp_ln538_16_reg_776;
reg   [15:0] out_data_9_reg_781;
wire   [0:0] icmp_ln538_17_fu_398_p2;
reg   [0:0] icmp_ln538_17_reg_786;
reg   [15:0] out_data_11_reg_791;
wire   [0:0] icmp_ln538_18_fu_414_p2;
reg   [0:0] icmp_ln538_18_reg_796;
reg   [15:0] out_data_13_reg_801;
wire   [0:0] icmp_ln538_19_fu_430_p2;
reg   [0:0] icmp_ln538_19_reg_806;
reg   [15:0] trunc_ln2_reg_811;
wire   [0:0] icmp_ln538_20_fu_446_p2;
reg   [0:0] icmp_ln538_20_reg_816;
reg   [15:0] trunc_ln539_s_reg_821;
wire   [0:0] icmp_ln538_21_fu_462_p2;
reg   [0:0] icmp_ln538_21_reg_826;
reg   [15:0] trunc_ln539_11_reg_831;
wire   [0:0] icmp_ln538_22_fu_478_p2;
reg   [0:0] icmp_ln538_22_reg_836;
reg   [15:0] trunc_ln539_12_reg_841;
wire   [0:0] icmp_ln538_23_fu_494_p2;
reg   [0:0] icmp_ln538_23_reg_846;
reg   [15:0] trunc_ln539_13_reg_851;
wire   [0:0] icmp_ln538_24_fu_510_p2;
reg   [0:0] icmp_ln538_24_reg_856;
reg   [15:0] trunc_ln539_14_reg_861;
wire   [0:0] icmp_ln538_25_fu_526_p2;
reg   [0:0] icmp_ln538_25_reg_866;
reg   [15:0] trunc_ln539_15_reg_871;
wire   [0:0] icmp_ln538_26_fu_542_p2;
reg   [0:0] icmp_ln538_26_reg_876;
reg   [15:0] trunc_ln539_16_reg_881;
wire   [0:0] icmp_ln538_27_fu_558_p2;
reg   [0:0] icmp_ln538_27_reg_886;
reg   [15:0] trunc_ln539_17_reg_891;
wire   [0:0] icmp_ln538_28_fu_574_p2;
reg   [0:0] icmp_ln538_28_reg_896;
reg   [15:0] trunc_ln539_18_reg_901;
wire   [0:0] icmp_ln538_29_fu_590_p2;
reg   [0:0] icmp_ln538_29_reg_906;
reg   [15:0] trunc_ln539_19_reg_911;
wire   [0:0] icmp_ln538_30_fu_606_p2;
reg   [0:0] icmp_ln538_30_reg_916;
reg   [15:0] trunc_ln539_20_reg_921;
reg   [14:0] i_03_fu_170;
wire   [14:0] i_6_fu_201_p2;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage0_01001;
wire   [36:0] trunc_ln531_fu_212_p1;
wire   [36:0] trunc_ln531_s_fu_216_p4;
wire   [36:0] trunc_ln531_15_fu_226_p4;
wire   [36:0] trunc_ln531_16_fu_236_p4;
wire   [36:0] trunc_ln531_17_fu_246_p4;
wire   [36:0] trunc_ln531_18_fu_256_p4;
wire   [36:0] trunc_ln531_19_fu_266_p4;
wire   [36:0] trunc_ln531_20_fu_276_p4;
wire   [36:0] trunc_ln531_21_fu_286_p4;
wire   [36:0] trunc_ln531_22_fu_296_p4;
wire   [36:0] trunc_ln531_23_fu_306_p4;
wire   [36:0] trunc_ln531_24_fu_316_p4;
wire   [36:0] trunc_ln531_25_fu_326_p4;
wire   [36:0] trunc_ln531_26_fu_336_p4;
wire   [36:0] trunc_ln531_27_fu_346_p4;
wire   [36:0] trunc_ln531_28_fu_356_p4;
wire   [15:0] select_ln538_22_fu_712_p3;
wire   [15:0] select_ln538_21_fu_706_p3;
wire   [15:0] select_ln538_20_fu_700_p3;
wire   [15:0] select_ln538_19_fu_694_p3;
wire   [15:0] select_ln538_18_fu_688_p3;
wire   [15:0] select_ln538_17_fu_682_p3;
wire   [15:0] select_ln538_16_fu_676_p3;
wire   [15:0] select_ln538_15_fu_670_p3;
wire   [15:0] select_ln538_14_fu_664_p3;
wire   [15:0] select_ln538_13_fu_658_p3;
wire   [15:0] select_ln538_12_fu_652_p3;
wire   [15:0] select_ln538_fu_646_p3;
wire   [15:0] out_data_14_fu_640_p3;
wire   [15:0] out_data_12_fu_634_p3;
wire   [15:0] out_data_10_fu_628_p3;
wire   [15:0] out_data_8_fu_622_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_177;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_03_fu_170 = 15'd0;
end

folo_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_177)) begin
        if ((icmp_ln528_fu_195_p2 == 1'd0)) begin
            i_03_fu_170 <= i_6_fu_201_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_03_fu_170 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln538_16_reg_776 <= icmp_ln538_16_fu_382_p2;
        icmp_ln538_17_reg_786 <= icmp_ln538_17_fu_398_p2;
        icmp_ln538_18_reg_796 <= icmp_ln538_18_fu_414_p2;
        icmp_ln538_19_reg_806 <= icmp_ln538_19_fu_430_p2;
        icmp_ln538_20_reg_816 <= icmp_ln538_20_fu_446_p2;
        icmp_ln538_21_reg_826 <= icmp_ln538_21_fu_462_p2;
        icmp_ln538_22_reg_836 <= icmp_ln538_22_fu_478_p2;
        icmp_ln538_23_reg_846 <= icmp_ln538_23_fu_494_p2;
        icmp_ln538_24_reg_856 <= icmp_ln538_24_fu_510_p2;
        icmp_ln538_25_reg_866 <= icmp_ln538_25_fu_526_p2;
        icmp_ln538_26_reg_876 <= icmp_ln538_26_fu_542_p2;
        icmp_ln538_27_reg_886 <= icmp_ln538_27_fu_558_p2;
        icmp_ln538_28_reg_896 <= icmp_ln538_28_fu_574_p2;
        icmp_ln538_29_reg_906 <= icmp_ln538_29_fu_590_p2;
        icmp_ln538_30_reg_916 <= icmp_ln538_30_fu_606_p2;
        icmp_ln538_reg_766 <= icmp_ln538_fu_366_p2;
        out_data_11_reg_791 <= {{layer3_out_dout[99:84]}};
        out_data_13_reg_801 <= {{layer3_out_dout[136:121]}};
        out_data_9_reg_781 <= {{layer3_out_dout[62:47]}};
        out_data_reg_771 <= {{layer3_out_dout[25:10]}};
        trunc_ln2_reg_811 <= {{layer3_out_dout[173:158]}};
        trunc_ln539_11_reg_831 <= {{layer3_out_dout[247:232]}};
        trunc_ln539_12_reg_841 <= {{layer3_out_dout[284:269]}};
        trunc_ln539_13_reg_851 <= {{layer3_out_dout[321:306]}};
        trunc_ln539_14_reg_861 <= {{layer3_out_dout[358:343]}};
        trunc_ln539_15_reg_871 <= {{layer3_out_dout[395:380]}};
        trunc_ln539_16_reg_881 <= {{layer3_out_dout[432:417]}};
        trunc_ln539_17_reg_891 <= {{layer3_out_dout[469:454]}};
        trunc_ln539_18_reg_901 <= {{layer3_out_dout[506:491]}};
        trunc_ln539_19_reg_911 <= {{layer3_out_dout[543:528]}};
        trunc_ln539_20_reg_921 <= {{layer3_out_dout[580:565]}};
        trunc_ln539_s_reg_821 <= {{layer3_out_dout[210:195]}};
    end
end

always @ (*) begin
    if (((icmp_ln528_fu_195_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 15'd0;
    end else begin
        ap_sig_allocacmp_i = i_03_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer3_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer5_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_177 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_6_fu_201_p2 = (ap_sig_allocacmp_i + 15'd1);

assign icmp_ln528_fu_195_p2 = ((ap_sig_allocacmp_i == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln538_16_fu_382_p2 = (($signed(trunc_ln531_s_fu_216_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_17_fu_398_p2 = (($signed(trunc_ln531_15_fu_226_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_18_fu_414_p2 = (($signed(trunc_ln531_16_fu_236_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_19_fu_430_p2 = (($signed(trunc_ln531_17_fu_246_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_20_fu_446_p2 = (($signed(trunc_ln531_18_fu_256_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_21_fu_462_p2 = (($signed(trunc_ln531_19_fu_266_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_22_fu_478_p2 = (($signed(trunc_ln531_20_fu_276_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_23_fu_494_p2 = (($signed(trunc_ln531_21_fu_286_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_24_fu_510_p2 = (($signed(trunc_ln531_22_fu_296_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_25_fu_526_p2 = (($signed(trunc_ln531_23_fu_306_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_26_fu_542_p2 = (($signed(trunc_ln531_24_fu_316_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_27_fu_558_p2 = (($signed(trunc_ln531_25_fu_326_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_28_fu_574_p2 = (($signed(trunc_ln531_26_fu_336_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_29_fu_590_p2 = (($signed(trunc_ln531_27_fu_346_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_30_fu_606_p2 = (($signed(trunc_ln531_28_fu_356_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_366_p2 = (($signed(trunc_ln531_fu_212_p1) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign layer5_out_din = {{{{{{{{{{{{{{{{select_ln538_22_fu_712_p3}, {select_ln538_21_fu_706_p3}}, {select_ln538_20_fu_700_p3}}, {select_ln538_19_fu_694_p3}}, {select_ln538_18_fu_688_p3}}, {select_ln538_17_fu_682_p3}}, {select_ln538_16_fu_676_p3}}, {select_ln538_15_fu_670_p3}}, {select_ln538_14_fu_664_p3}}, {select_ln538_13_fu_658_p3}}, {select_ln538_12_fu_652_p3}}, {select_ln538_fu_646_p3}}, {out_data_14_fu_640_p3}}, {out_data_12_fu_634_p3}}, {out_data_10_fu_628_p3}}, {out_data_8_fu_622_p3}};

assign out_data_10_fu_628_p3 = ((icmp_ln538_16_reg_776[0:0] == 1'b1) ? out_data_9_reg_781 : 16'd0);

assign out_data_12_fu_634_p3 = ((icmp_ln538_17_reg_786[0:0] == 1'b1) ? out_data_11_reg_791 : 16'd0);

assign out_data_14_fu_640_p3 = ((icmp_ln538_18_reg_796[0:0] == 1'b1) ? out_data_13_reg_801 : 16'd0);

assign out_data_8_fu_622_p3 = ((icmp_ln538_reg_766[0:0] == 1'b1) ? out_data_reg_771 : 16'd0);

assign select_ln538_12_fu_652_p3 = ((icmp_ln538_20_reg_816[0:0] == 1'b1) ? trunc_ln539_s_reg_821 : 16'd0);

assign select_ln538_13_fu_658_p3 = ((icmp_ln538_21_reg_826[0:0] == 1'b1) ? trunc_ln539_11_reg_831 : 16'd0);

assign select_ln538_14_fu_664_p3 = ((icmp_ln538_22_reg_836[0:0] == 1'b1) ? trunc_ln539_12_reg_841 : 16'd0);

assign select_ln538_15_fu_670_p3 = ((icmp_ln538_23_reg_846[0:0] == 1'b1) ? trunc_ln539_13_reg_851 : 16'd0);

assign select_ln538_16_fu_676_p3 = ((icmp_ln538_24_reg_856[0:0] == 1'b1) ? trunc_ln539_14_reg_861 : 16'd0);

assign select_ln538_17_fu_682_p3 = ((icmp_ln538_25_reg_866[0:0] == 1'b1) ? trunc_ln539_15_reg_871 : 16'd0);

assign select_ln538_18_fu_688_p3 = ((icmp_ln538_26_reg_876[0:0] == 1'b1) ? trunc_ln539_16_reg_881 : 16'd0);

assign select_ln538_19_fu_694_p3 = ((icmp_ln538_27_reg_886[0:0] == 1'b1) ? trunc_ln539_17_reg_891 : 16'd0);

assign select_ln538_20_fu_700_p3 = ((icmp_ln538_28_reg_896[0:0] == 1'b1) ? trunc_ln539_18_reg_901 : 16'd0);

assign select_ln538_21_fu_706_p3 = ((icmp_ln538_29_reg_906[0:0] == 1'b1) ? trunc_ln539_19_reg_911 : 16'd0);

assign select_ln538_22_fu_712_p3 = ((icmp_ln538_30_reg_916[0:0] == 1'b1) ? trunc_ln539_20_reg_921 : 16'd0);

assign select_ln538_fu_646_p3 = ((icmp_ln538_19_reg_806[0:0] == 1'b1) ? trunc_ln2_reg_811 : 16'd0);

assign start_out = real_start;

assign trunc_ln531_15_fu_226_p4 = {{layer3_out_dout[110:74]}};

assign trunc_ln531_16_fu_236_p4 = {{layer3_out_dout[147:111]}};

assign trunc_ln531_17_fu_246_p4 = {{layer3_out_dout[184:148]}};

assign trunc_ln531_18_fu_256_p4 = {{layer3_out_dout[221:185]}};

assign trunc_ln531_19_fu_266_p4 = {{layer3_out_dout[258:222]}};

assign trunc_ln531_20_fu_276_p4 = {{layer3_out_dout[295:259]}};

assign trunc_ln531_21_fu_286_p4 = {{layer3_out_dout[332:296]}};

assign trunc_ln531_22_fu_296_p4 = {{layer3_out_dout[369:333]}};

assign trunc_ln531_23_fu_306_p4 = {{layer3_out_dout[406:370]}};

assign trunc_ln531_24_fu_316_p4 = {{layer3_out_dout[443:407]}};

assign trunc_ln531_25_fu_326_p4 = {{layer3_out_dout[480:444]}};

assign trunc_ln531_26_fu_336_p4 = {{layer3_out_dout[517:481]}};

assign trunc_ln531_27_fu_346_p4 = {{layer3_out_dout[554:518]}};

assign trunc_ln531_28_fu_356_p4 = {{layer3_out_dout[591:555]}};

assign trunc_ln531_fu_212_p1 = layer3_out_dout[36:0];

assign trunc_ln531_s_fu_216_p4 = {{layer3_out_dout[73:37]}};

endmodule //folo_thresholded_relu_array_ap_fixed_array_ap_fixed_16u_thresholdedrelu_config5_s
