// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module folo_thresholded_relu_array_ap_fixed_array_ap_fixed_16u_thresholdedrelu_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer7_out_dout,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap,
        layer7_out_empty_n,
        layer7_out_read,
        layer9_out_din,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_full_n,
        layer9_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [655:0] layer7_out_dout;
input  [12:0] layer7_out_num_data_valid;
input  [12:0] layer7_out_fifo_cap;
input   layer7_out_empty_n;
output   layer7_out_read;
output  [255:0] layer9_out_din;
input  [12:0] layer9_out_num_data_valid;
input  [12:0] layer9_out_fifo_cap;
input   layer9_out_full_n;
output   layer9_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer7_out_read;
reg layer9_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln528_fu_195_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer7_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer9_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln538_fu_366_p2;
reg   [0:0] icmp_ln538_reg_766;
reg   [15:0] out_data_reg_771;
wire   [0:0] icmp_ln538_1_fu_382_p2;
reg   [0:0] icmp_ln538_1_reg_776;
reg   [15:0] out_data_2_reg_781;
wire   [0:0] icmp_ln538_2_fu_398_p2;
reg   [0:0] icmp_ln538_2_reg_786;
reg   [15:0] out_data_4_reg_791;
wire   [0:0] icmp_ln538_3_fu_414_p2;
reg   [0:0] icmp_ln538_3_reg_796;
reg   [15:0] out_data_6_reg_801;
wire   [0:0] icmp_ln538_4_fu_430_p2;
reg   [0:0] icmp_ln538_4_reg_806;
reg   [15:0] trunc_ln1_reg_811;
wire   [0:0] icmp_ln538_5_fu_446_p2;
reg   [0:0] icmp_ln538_5_reg_816;
reg   [15:0] trunc_ln539_1_reg_821;
wire   [0:0] icmp_ln538_6_fu_462_p2;
reg   [0:0] icmp_ln538_6_reg_826;
reg   [15:0] trunc_ln539_2_reg_831;
wire   [0:0] icmp_ln538_7_fu_478_p2;
reg   [0:0] icmp_ln538_7_reg_836;
reg   [15:0] trunc_ln539_3_reg_841;
wire   [0:0] icmp_ln538_8_fu_494_p2;
reg   [0:0] icmp_ln538_8_reg_846;
reg   [15:0] trunc_ln539_4_reg_851;
wire   [0:0] icmp_ln538_9_fu_510_p2;
reg   [0:0] icmp_ln538_9_reg_856;
reg   [15:0] trunc_ln539_5_reg_861;
wire   [0:0] icmp_ln538_10_fu_526_p2;
reg   [0:0] icmp_ln538_10_reg_866;
reg   [15:0] trunc_ln539_6_reg_871;
wire   [0:0] icmp_ln538_11_fu_542_p2;
reg   [0:0] icmp_ln538_11_reg_876;
reg   [15:0] trunc_ln539_7_reg_881;
wire   [0:0] icmp_ln538_12_fu_558_p2;
reg   [0:0] icmp_ln538_12_reg_886;
reg   [15:0] trunc_ln539_8_reg_891;
wire   [0:0] icmp_ln538_13_fu_574_p2;
reg   [0:0] icmp_ln538_13_reg_896;
reg   [15:0] trunc_ln539_9_reg_901;
wire   [0:0] icmp_ln538_14_fu_590_p2;
reg   [0:0] icmp_ln538_14_reg_906;
reg   [15:0] trunc_ln539_s_reg_911;
wire   [0:0] icmp_ln538_15_fu_606_p2;
reg   [0:0] icmp_ln538_15_reg_916;
reg   [15:0] trunc_ln539_10_reg_921;
reg   [12:0] i_3_fu_170;
wire   [12:0] i_5_fu_201_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage0_01001;
wire   [40:0] trunc_ln531_fu_212_p1;
wire   [40:0] trunc_ln531_1_fu_216_p4;
wire   [40:0] trunc_ln531_2_fu_226_p4;
wire   [40:0] trunc_ln531_3_fu_236_p4;
wire   [40:0] trunc_ln531_4_fu_246_p4;
wire   [40:0] trunc_ln531_5_fu_256_p4;
wire   [40:0] trunc_ln531_6_fu_266_p4;
wire   [40:0] trunc_ln531_7_fu_276_p4;
wire   [40:0] trunc_ln531_8_fu_286_p4;
wire   [40:0] trunc_ln531_9_fu_296_p4;
wire   [40:0] trunc_ln531_s_fu_306_p4;
wire   [40:0] trunc_ln531_10_fu_316_p4;
wire   [40:0] trunc_ln531_11_fu_326_p4;
wire   [40:0] trunc_ln531_12_fu_336_p4;
wire   [40:0] trunc_ln531_13_fu_346_p4;
wire   [40:0] trunc_ln531_14_fu_356_p4;
wire   [15:0] select_ln538_11_fu_712_p3;
wire   [15:0] select_ln538_10_fu_706_p3;
wire   [15:0] select_ln538_9_fu_700_p3;
wire   [15:0] select_ln538_8_fu_694_p3;
wire   [15:0] select_ln538_7_fu_688_p3;
wire   [15:0] select_ln538_6_fu_682_p3;
wire   [15:0] select_ln538_5_fu_676_p3;
wire   [15:0] select_ln538_4_fu_670_p3;
wire   [15:0] select_ln538_3_fu_664_p3;
wire   [15:0] select_ln538_2_fu_658_p3;
wire   [15:0] select_ln538_1_fu_652_p3;
wire   [15:0] select_ln538_fu_646_p3;
wire   [15:0] out_data_7_fu_640_p3;
wire   [15:0] out_data_5_fu_634_p3;
wire   [15:0] out_data_3_fu_628_p3;
wire   [15:0] out_data_1_fu_622_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_177;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_3_fu_170 = 13'd0;
end

folo_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_177)) begin
        if ((icmp_ln528_fu_195_p2 == 1'd0)) begin
            i_3_fu_170 <= i_5_fu_201_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_3_fu_170 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln538_10_reg_866 <= icmp_ln538_10_fu_526_p2;
        icmp_ln538_11_reg_876 <= icmp_ln538_11_fu_542_p2;
        icmp_ln538_12_reg_886 <= icmp_ln538_12_fu_558_p2;
        icmp_ln538_13_reg_896 <= icmp_ln538_13_fu_574_p2;
        icmp_ln538_14_reg_906 <= icmp_ln538_14_fu_590_p2;
        icmp_ln538_15_reg_916 <= icmp_ln538_15_fu_606_p2;
        icmp_ln538_1_reg_776 <= icmp_ln538_1_fu_382_p2;
        icmp_ln538_2_reg_786 <= icmp_ln538_2_fu_398_p2;
        icmp_ln538_3_reg_796 <= icmp_ln538_3_fu_414_p2;
        icmp_ln538_4_reg_806 <= icmp_ln538_4_fu_430_p2;
        icmp_ln538_5_reg_816 <= icmp_ln538_5_fu_446_p2;
        icmp_ln538_6_reg_826 <= icmp_ln538_6_fu_462_p2;
        icmp_ln538_7_reg_836 <= icmp_ln538_7_fu_478_p2;
        icmp_ln538_8_reg_846 <= icmp_ln538_8_fu_494_p2;
        icmp_ln538_9_reg_856 <= icmp_ln538_9_fu_510_p2;
        icmp_ln538_reg_766 <= icmp_ln538_fu_366_p2;
        out_data_2_reg_781 <= {{layer7_out_dout[66:51]}};
        out_data_4_reg_791 <= {{layer7_out_dout[107:92]}};
        out_data_6_reg_801 <= {{layer7_out_dout[148:133]}};
        out_data_reg_771 <= {{layer7_out_dout[25:10]}};
        trunc_ln1_reg_811 <= {{layer7_out_dout[189:174]}};
        trunc_ln539_10_reg_921 <= {{layer7_out_dout[640:625]}};
        trunc_ln539_1_reg_821 <= {{layer7_out_dout[230:215]}};
        trunc_ln539_2_reg_831 <= {{layer7_out_dout[271:256]}};
        trunc_ln539_3_reg_841 <= {{layer7_out_dout[312:297]}};
        trunc_ln539_4_reg_851 <= {{layer7_out_dout[353:338]}};
        trunc_ln539_5_reg_861 <= {{layer7_out_dout[394:379]}};
        trunc_ln539_6_reg_871 <= {{layer7_out_dout[435:420]}};
        trunc_ln539_7_reg_881 <= {{layer7_out_dout[476:461]}};
        trunc_ln539_8_reg_891 <= {{layer7_out_dout[517:502]}};
        trunc_ln539_9_reg_901 <= {{layer7_out_dout[558:543]}};
        trunc_ln539_s_reg_911 <= {{layer7_out_dout[599:584]}};
    end
end

always @ (*) begin
    if (((icmp_ln528_fu_195_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 13'd0;
    end else begin
        ap_sig_allocacmp_i = i_3_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer7_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer9_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_177 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_5_fu_201_p2 = (ap_sig_allocacmp_i + 13'd1);

assign icmp_ln528_fu_195_p2 = ((ap_sig_allocacmp_i == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln538_10_fu_526_p2 = (($signed(trunc_ln531_s_fu_306_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_11_fu_542_p2 = (($signed(trunc_ln531_10_fu_316_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_12_fu_558_p2 = (($signed(trunc_ln531_11_fu_326_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_13_fu_574_p2 = (($signed(trunc_ln531_12_fu_336_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_14_fu_590_p2 = (($signed(trunc_ln531_13_fu_346_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_15_fu_606_p2 = (($signed(trunc_ln531_14_fu_356_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_1_fu_382_p2 = (($signed(trunc_ln531_1_fu_216_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_2_fu_398_p2 = (($signed(trunc_ln531_2_fu_226_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_3_fu_414_p2 = (($signed(trunc_ln531_3_fu_236_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_4_fu_430_p2 = (($signed(trunc_ln531_4_fu_246_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_5_fu_446_p2 = (($signed(trunc_ln531_5_fu_256_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_6_fu_462_p2 = (($signed(trunc_ln531_6_fu_266_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_7_fu_478_p2 = (($signed(trunc_ln531_7_fu_276_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_8_fu_494_p2 = (($signed(trunc_ln531_8_fu_286_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_9_fu_510_p2 = (($signed(trunc_ln531_9_fu_296_p4) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_366_p2 = (($signed(trunc_ln531_fu_212_p1) > $signed(41'd0)) ? 1'b1 : 1'b0);

assign layer9_out_din = {{{{{{{{{{{{{{{{select_ln538_11_fu_712_p3}, {select_ln538_10_fu_706_p3}}, {select_ln538_9_fu_700_p3}}, {select_ln538_8_fu_694_p3}}, {select_ln538_7_fu_688_p3}}, {select_ln538_6_fu_682_p3}}, {select_ln538_5_fu_676_p3}}, {select_ln538_4_fu_670_p3}}, {select_ln538_3_fu_664_p3}}, {select_ln538_2_fu_658_p3}}, {select_ln538_1_fu_652_p3}}, {select_ln538_fu_646_p3}}, {out_data_7_fu_640_p3}}, {out_data_5_fu_634_p3}}, {out_data_3_fu_628_p3}}, {out_data_1_fu_622_p3}};

assign out_data_1_fu_622_p3 = ((icmp_ln538_reg_766[0:0] == 1'b1) ? out_data_reg_771 : 16'd0);

assign out_data_3_fu_628_p3 = ((icmp_ln538_1_reg_776[0:0] == 1'b1) ? out_data_2_reg_781 : 16'd0);

assign out_data_5_fu_634_p3 = ((icmp_ln538_2_reg_786[0:0] == 1'b1) ? out_data_4_reg_791 : 16'd0);

assign out_data_7_fu_640_p3 = ((icmp_ln538_3_reg_796[0:0] == 1'b1) ? out_data_6_reg_801 : 16'd0);

assign select_ln538_10_fu_706_p3 = ((icmp_ln538_14_reg_906[0:0] == 1'b1) ? trunc_ln539_s_reg_911 : 16'd0);

assign select_ln538_11_fu_712_p3 = ((icmp_ln538_15_reg_916[0:0] == 1'b1) ? trunc_ln539_10_reg_921 : 16'd0);

assign select_ln538_1_fu_652_p3 = ((icmp_ln538_5_reg_816[0:0] == 1'b1) ? trunc_ln539_1_reg_821 : 16'd0);

assign select_ln538_2_fu_658_p3 = ((icmp_ln538_6_reg_826[0:0] == 1'b1) ? trunc_ln539_2_reg_831 : 16'd0);

assign select_ln538_3_fu_664_p3 = ((icmp_ln538_7_reg_836[0:0] == 1'b1) ? trunc_ln539_3_reg_841 : 16'd0);

assign select_ln538_4_fu_670_p3 = ((icmp_ln538_8_reg_846[0:0] == 1'b1) ? trunc_ln539_4_reg_851 : 16'd0);

assign select_ln538_5_fu_676_p3 = ((icmp_ln538_9_reg_856[0:0] == 1'b1) ? trunc_ln539_5_reg_861 : 16'd0);

assign select_ln538_6_fu_682_p3 = ((icmp_ln538_10_reg_866[0:0] == 1'b1) ? trunc_ln539_6_reg_871 : 16'd0);

assign select_ln538_7_fu_688_p3 = ((icmp_ln538_11_reg_876[0:0] == 1'b1) ? trunc_ln539_7_reg_881 : 16'd0);

assign select_ln538_8_fu_694_p3 = ((icmp_ln538_12_reg_886[0:0] == 1'b1) ? trunc_ln539_8_reg_891 : 16'd0);

assign select_ln538_9_fu_700_p3 = ((icmp_ln538_13_reg_896[0:0] == 1'b1) ? trunc_ln539_9_reg_901 : 16'd0);

assign select_ln538_fu_646_p3 = ((icmp_ln538_4_reg_806[0:0] == 1'b1) ? trunc_ln1_reg_811 : 16'd0);

assign start_out = real_start;

assign trunc_ln531_10_fu_316_p4 = {{layer7_out_dout[491:451]}};

assign trunc_ln531_11_fu_326_p4 = {{layer7_out_dout[532:492]}};

assign trunc_ln531_12_fu_336_p4 = {{layer7_out_dout[573:533]}};

assign trunc_ln531_13_fu_346_p4 = {{layer7_out_dout[614:574]}};

assign trunc_ln531_14_fu_356_p4 = {{layer7_out_dout[655:615]}};

assign trunc_ln531_1_fu_216_p4 = {{layer7_out_dout[81:41]}};

assign trunc_ln531_2_fu_226_p4 = {{layer7_out_dout[122:82]}};

assign trunc_ln531_3_fu_236_p4 = {{layer7_out_dout[163:123]}};

assign trunc_ln531_4_fu_246_p4 = {{layer7_out_dout[204:164]}};

assign trunc_ln531_5_fu_256_p4 = {{layer7_out_dout[245:205]}};

assign trunc_ln531_6_fu_266_p4 = {{layer7_out_dout[286:246]}};

assign trunc_ln531_7_fu_276_p4 = {{layer7_out_dout[327:287]}};

assign trunc_ln531_8_fu_286_p4 = {{layer7_out_dout[368:328]}};

assign trunc_ln531_9_fu_296_p4 = {{layer7_out_dout[409:369]}};

assign trunc_ln531_fu_212_p1 = layer7_out_dout[40:0];

assign trunc_ln531_s_fu_306_p4 = {{layer7_out_dout[450:410]}};

endmodule //folo_thresholded_relu_array_ap_fixed_array_ap_fixed_16u_thresholdedrelu_config9_s
